name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello @${{ github.actor }}, Thank you for generating an issue to this project! Please wait while we get back to you.'
        pr-message: 'Hello @${{ github.actor }}, We love Pull Requests! Thank you for contributing to Face-Mask-Detection.'
